version: "3"
services:

  heroes-db:
    image: postgres:16
    container_name: heroes-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: superman
      POSTGRES_PASSWORD: superman
      POSTGRES_DB: heroes_database
    volumes:
      - ${PWD}/database/heroes-db/init/heroes.sql:/docker-entrypoint-initdb.d/init.sql
  villains-db:
    image: postgres:16
    container_name: villains-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: superman
      POSTGRES_PASSWORD: superman
      POSTGRES_DB: villains_database
    volumes:
      - ${PWD}/database/villains-db/init/villains.sql:/docker-entrypoint-initdb.d/init.sql
  locations-db:
    image: mariadb:11.5
    container_name: locations-db
    ports:
      - "3306:3306"
    environment:
      MARIADB_USER: locations
      MARIADB_PASSWORD: locations
      MARIADB_DATABASE: locations_database
      MARIADB_ROOT_PASSWORD: locations
      MARIADB_SKIP_TEST_DB: yes
    volumes:
      - ${PWD}/database/locations-db/init/initialize-tables.sql:/docker-entrypoint-initdb.d/1-init-tables.sql
